---
swagger: "2.0"
info:
  title: Loyalty API
  version: 1.0.0
host: internal.abgapiservices.com
basePath: /loyalty/v1
consumes:
- application/json
produces:
- application/json
paths:
  /partner:
    get:
      parameters:
      - $ref: '#/definitions/partner_code'
        name: partner_code
        description: ""
        in: query
        required: true
      - $ref: '#/definitions/language'
        name: language
        description: ""
        in: query
      - $ref: '#/definitions/channel'
        name: channel
        description: ""
        in: query
      - $ref: '#/definitions/transaction_id'
        name: transaction_id
        description: ""
        in: query
      - name: client_id
        description: Your client identifier.
        in: header
        required: true
        type: string
        maxLength: 50
        minLength: 8
      responses:
        "200":
          $ref: '#/responses/partner_v1_response'
          schema:
            $ref: '#/definitions/partner_v1_response'
          examples:
            application/json:
              status:
                request_time: 2018-10-25T12:01:54Z
                success:
                - code: "200"
                  message: Success
                  details: Loyalty details are successfully retrieved.
              transaction:
                id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
                system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
              domain:
                language: EN
              loyalty_discounts:
              - rate_qualifiers:
                  partner_loyalty:
                    program: SANS CARTE
                  partner_discount:
                    program: SANS CARTE
                mapped_discounts:
                - brand: Avis
                  code: X5212058
                  percent: 10
                  free_options:
                    eligible_extras:
                      quantity: 0
                - brand: Budget
                  code: L824502
                  percent: 10
                  free_options:
                    eligible_extras:
                      quantity: 0
              - rate_qualifiers:
                  partner_loyalty:
                    program: VOYAGEUR
                  partner_discount:
                    program: SANS CARTE
                mapped_discounts:
                - brand: Avis
                  code: X5212059
                  percent: 15
                  free_options:
                    eligible_extras:
                      quantity: 1
                    eligible_codes:
                    - ADD
                    - GPS
                    - BBS
                    - CBS
                    - CSS
                    - SKR
                    - SNC
                - brand: Budget
                  code: L824502
                  percent: 15
                  free_options:
                    eligible_extras:
                      quantity: 0
        "400":
          $ref: '#/responses/error_response_400'
          schema:
            $ref: '#/definitions/error_400'
          examples:
            application/json:
              status:
                request_time: 2019-01-04T15:15:30Z
                request_errors: 1
                errors:
                - code: "400"
                  message: Bad request
                  reason: invalid_request
                  details: Specified parameter <parameter name> is not valid
              transaction:
                id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
                system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
        "404":
          $ref: '#/responses/error_response_404'
          schema:
            $ref: '#/definitions/error_404'
          examples:
            application/json:
              status:
                request_time: 2019-01-04T15:15:30Z
                request_errors: 1
                errors:
                - code: "404"
                  message: Resource not found
                  reason: resource_failure
                  details: Server cannot find the requested resource. This may be
                    due to incorrect URI or a resource that is not available.
              transaction:
                id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
                system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
        "405":
          $ref: '#/responses/error_response_405'
          schema:
            $ref: '#/definitions/error_405'
          examples:
            application/json:
              status:
                request_time: 2019-01-04T15:15:30Z
                request_errors: 1
                errors:
                - code: "405"
                  message: Method not allowed
                  reason: invalid_request
                  details: Invalid HTTP message
              transaction:
                id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
                system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
        "406":
          $ref: '#/responses/error_responce_406'
          schema:
            $ref: '#/definitions/error_406'
          examples:
            application/json:
              status:
                request_time: 2019-01-04T15:15:30Z
                request_errors: 1
                errors:
                - code: "406"
                  message: Invalid content type
                  reason: not_accecptable
                  details: Invalid content type in the request payload
              transaction:
                id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
                system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
        "415":
          $ref: '#/responses/error_response_415'
          schema:
            $ref: '#/definitions/error_415'
          examples:
            application/json:
              status:
                request_time: 2019-01-04T15:15:30Z
                request_errors: 1
                errors:
                - code: "415"
                  message: Unsupported media type
                  reason: unsupported media type
                  details: ""
              transaction:
                id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
                system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
        "500":
          $ref: '#/responses/error_response_500'
          schema:
            $ref: '#/definitions/error_500'
          examples:
            application/json:
              status:
                request_time: 2019-01-04T15:15:30Z
                request_errors: 1
                errors:
                - code: "500"
                  message: Service exception
                  reason: System exception from e-com backend.
                  details: System Exception occurred. Please check the log for details.
              transaction:
                id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
                system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
  /program:
    post:
      parameters:
      - name: body
        schema:
          $ref: '#/definitions/partner_program_v1_request'
        in: body
        required: true
      - name: client_id
        description: Your client identifier.
        in: header
        required: true
        type: string
        maxLength: 50
        minLength: 8
      responses:
        "200":
          $ref: '#/responses/partner_program_v1_response'
          schema:
            $ref: '#/definitions/partner_program_v1_response'
          examples:
            application/json:
              status:
                request_time: 2018-10-25T12:01:54Z
                success:
                - code: "200"
                  message: Success
                  details: Loyalty details are successfully retrieved.
              transaction:
                id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
                system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
              domain:
                language: EN
              loyalty_discounts:
              - rate_qualifiers:
                  partner_loyalty:
                    program: Voyageur
                  partner_discount:
                    program: San carte
                mapped_discounts:
                - brand: Avis
                  code: X5212064
                  percent: 15
                  free_options:
                    eligible_extras:
                      quantity: 1
                    eligible_codes:
                    - ADD
                    - GPS
                    - BBS
                    - CBS
                    - CSS
                    - SKR
                    - SNC
                - brand: Budget
                  code: L824502
                  percent: 10
                  free_options:
                    eligible_extras:
                      quantity: 0
                best_discount: true
              - rate_qualifiers:
                  partner_loyalty:
                    program: GRAND VOYAGEUR LE CLUB
                  partner_discount:
                    program: Carte Jeune
                mapped_discounts:
                - brand: Avis
                  code: X5212067
                  percent: 10
                  free_options:
                    eligible_extras:
                      quantity: 1
                    eligible_codes:
                    - ADD
                    - GPS
                    - BBS
                    - CBS
                    - CSS
                    - SKR
                    - SNC
                - brand: Budget
                  code: L824502
                  percent: 10
                  free_options:
                    eligible_extras:
                      quantity: 0
        "400":
          $ref: '#/responses/error_response_400'
          schema:
            $ref: '#/definitions/error_400'
          examples:
            application/json:
              status:
                request_time: 2019-01-04T15:15:30Z
                request_errors: 1
                errors:
                - code: "400"
                  message: Bad request
                  reason: invalid_request
                  details: Specified parameter <parameter name> is not valid
              transaction:
                id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
                system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
        "404":
          $ref: '#/responses/error_response_404'
          schema:
            $ref: '#/definitions/error_405'
          examples:
            application/json:
              status:
                request_time: 2019-01-04T15:15:30Z
                request_errors: 1
                errors:
                - code: "404"
                  message: Resource not found
                  reason: resource_failure
                  details: Server cannot find the requested resource. This may be
                    due to incorrect URI or a resource that is not available.
              transaction:
                id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
                system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
        "405":
          $ref: '#/responses/error_response_405'
          schema:
            $ref: '#/definitions/error_405'
          examples:
            application/json:
              status:
                request_time: 2019-01-04T15:15:30Z
                request_errors: 1
                errors:
                - code: "405"
                  message: Method not allowed
                  reason: invalid_request
                  details: Invalid HTTP message
              transaction:
                id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
                system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
        "406":
          $ref: '#/responses/error_responce_406'
          schema:
            $ref: '#/definitions/error_406'
          examples:
            application/json:
              status:
                request_time: 2019-01-04T15:15:30Z
                request_errors: 1
                errors:
                - code: "406"
                  message: Invalid content type
                  reason: not_accecptable
                  details: Invalid content type in the request payload
              transaction:
                id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
                system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
        "415":
          $ref: '#/responses/error_response_415'
          schema:
            $ref: '#/definitions/error_415'
          examples:
            application/json:
              status:
                request_time: 2019-01-04T15:15:30Z
                request_errors: 1
                errors:
                - code: "415"
                  message: Unsupported media type
                  reason: unsupported media type
                  details: ""
              transaction:
                id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
                system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
        "500":
          $ref: '#/responses/error_response_500'
          schema:
            $ref: '#/definitions/error_500'
          examples:
            application/json:
              status:
                request_time: 2019-01-04T15:15:30Z
                request_errors: 1
                errors:
                - code: "500"
                  message: Service exception
                  reason: System exception from e-com backend.
                  details: System Exception occurred. Please check the log for details.
              transaction:
                id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
                system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
      security:
      - OAuth2.0: []
definitions:
  partner_program_v1_request:
    description: Commercially agreed partner loyalties and discounts to be sent in
      the request.
    type: object
    properties:
      transaction:
        $ref: '#/definitions/transaction'
        description: ""
      partner:
        $ref: '#/definitions/partner'
        description: ""
      domain:
        $ref: '#/definitions/domain'
        description: ""
      loyalty_discounts:
        description: ""
    example:
      transaction:
        id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
      partner:
        code: SNCF
      domain:
        language: EN
        channel: website
      loyalty_discounts:
      - rate_qualifiers:
          partner_loyalty:
            program: Voyageur
          partner_discount:
            program: Carte Jeune
        driver: primary
      - rate_qualifiers:
          partner_loyalty:
            program: GRAND VOYAGEUR LE CLUB
          partner_discount:
            program: Carte Jeune
        driver: secondary
  abg_location_code:
    $ref: apicurio:203#/definitions/abg_location_code
  address:
    $ref: apicurio:203#/definitions/address
  age:
    $ref: apicurio:203#/definitions/age
  airline_code:
    $ref: apicurio:203#/definitions/airline_code
  amount:
    $ref: apicurio:203#/definitions/amount
  arrival_flight:
    $ref: apicurio:203#/definitions/arrival_flight
  arrival_train:
    $ref: apicurio:203#/definitions/arrival_train
  brand:
    $ref: apicurio:203#/definitions/brand
  brands:
    $ref: apicurio:203#/definitions/brands
  calender:
    $ref: apicurio:203#/definitions/calender
  car_rental:
    $ref: apicurio:203#/definitions/car_rental
  channel:
    $ref: apicurio:203#/definitions/channel
  city:
    $ref: apicurio:203#/definitions/city
  class_code:
    $ref: apicurio:203#/definitions/class_code
  code:
    $ref: apicurio:203#/definitions/code
  commercial_discount:
    $ref: apicurio:203#/definitions/commercial_discount
  confirmation:
    $ref: apicurio:203#/definitions/confirmation
  contact:
    $ref: apicurio:203#/definitions/contact
  context:
    $ref: apicurio:203#/definitions/context
  coordinate:
    $ref: apicurio:203#/definitions/coordinate
  country_code:
    $ref: apicurio:203#/definitions/country_code
  coupon:
    $ref: apicurio:203#/definitions/coupon
  coupon_type:
    $ref: apicurio:203#/definitions/coupon_type
  currency:
    $ref: apicurio:203#/definitions/currency
  date:
    $ref: apicurio:203#/definitions/date
  date_range:
    $ref: apicurio:203#/definitions/date_range
  date_time:
    $ref: apicurio:203#/definitions/date_time
  day_of_week:
    $ref: apicurio:203#/definitions/day_of_week
  days:
    $ref: apicurio:203#/definitions/days
  departure_flight:
    $ref: apicurio:203#/definitions/departure_flight
  departure_train:
    $ref: apicurio:203#/definitions/departure_train
  disclaimer:
    $ref: apicurio:203#/definitions/disclaimer
  discount:
    $ref: apicurio:203#/definitions/discount
  discount_code:
    $ref: apicurio:203#/definitions/discount_code
  distance:
    $ref: apicurio:203#/definitions/distance
  distance_unit:
    $ref: apicurio:203#/definitions/distance_unit
  domain:
    $ref: apicurio:203#/definitions/domain
  driver:
    $ref: apicurio:203#/definitions/driver
  drivetrain:
    $ref: apicurio:203#/definitions/drivetrain
  dropoff_date:
    $ref: apicurio:203#/definitions/dropoff_date
  dropoff_location:
    $ref: apicurio:203#/definitions/dropoff_location
  error_400:
    $ref: apicurio:203#/definitions/error_400
  error_404:
    $ref: apicurio:203#/definitions/error_404
  error_405:
    $ref: apicurio:203#/definitions/error_405
  error_406:
    $ref: apicurio:203#/definitions/error_406
  error_415:
    $ref: apicurio:203#/definitions/error_415
  error_500:
    $ref: apicurio:203#/definitions/error_500
  error_details:
    $ref: apicurio:203#/definitions/error_details
  error_response:
    $ref: apicurio:203#/definitions/error_response
  error_response_400:
    $ref: apicurio:203#/definitions/error_response_400
  error_status:
    $ref: apicurio:203#/definitions/error_status
  extra:
    $ref: apicurio:203#/definitions/extra
  fee:
    $ref: apicurio:203#/definitions/fee
  flight_class:
    $ref: apicurio:203#/definitions/flight_class
  free_options:
    $ref: apicurio:203#/definitions/free_options
  fule_type:
    $ref: apicurio:203#/definitions/fule_type
  holiday:
    $ref: apicurio:203#/definitions/holiday
  hour:
    $ref: apicurio:203#/definitions/hour
  hours:
    $ref: apicurio:203#/definitions/hours
  http_code:
    $ref: apicurio:203#/definitions/http_code
  iata_number:
    $ref: apicurio:203#/definitions/iata_number
  insurance:
    $ref: apicurio:203#/definitions/insurance
  insurance_code:
    $ref: apicurio:203#/definitions/insurance_code
  insurance_name:
    $ref: apicurio:203#/definitions/insurance_name
  insurance_selection_note:
    $ref: apicurio:203#/definitions/insurance_selection_note
  journey_preference:
    $ref: apicurio:203#/definitions/journey_preference
  journey_type:
    $ref: apicurio:203#/definitions/journey_type
  language:
    $ref: apicurio:203#/definitions/language
  location:
    $ref: apicurio:203#/definitions/location
  location_code:
    $ref: apicurio:203#/definitions/location_code
  loyalty:
    $ref: apicurio:203#/definitions/loyalty
  luggage_capacity:
    $ref: apicurio:203#/definitions/luggage_capacity
  meet_and_greet:
    $ref: apicurio:203#/definitions/meet_and_greet
  meet_greet:
    $ref: apicurio:203#/definitions/meet_greet
  membership:
    $ref: apicurio:203#/definitions/membership
  name:
    $ref: apicurio:203#/definitions/name
  offer_preferences:
    $ref: apicurio:203#/definitions/offer_preferences
  offers:
    $ref: apicurio:203#/definitions/offers
  partial_success_status:
    $ref: apicurio:203#/definitions/partial_success_status
  partner_code:
    $ref: apicurio:203#/definitions/partner_code
  partner_discount:
    $ref: apicurio:203#/definitions/partner_discount
  partner_location_codes:
    $ref: apicurio:203#/definitions/partner_location_codes
  partner_loyalty:
    $ref: apicurio:203#/definitions/partner_loyalty
  partner_name:
    $ref: apicurio:203#/definitions/partner_name
  partner_program:
    $ref: apicurio:203#/definitions/partner_program
  passenger:
    $ref: apicurio:203#/definitions/passenger
  pay_later:
    $ref: apicurio:203#/definitions/pay_later
  pay_now:
    $ref: apicurio:203#/definitions/pay_now
  personalization:
    $ref: apicurio:203#/definitions/personalization
  pickup_date:
    $ref: apicurio:203#/definitions/pickup_date
  pickup_location:
    $ref: apicurio:203#/definitions/pickup_location
  product:
    $ref: apicurio:203#/definitions/product
  product_code:
    $ref: apicurio:203#/definitions/product_code
  product_type:
    $ref: apicurio:203#/definitions/product_type
  program_id:
    $ref: apicurio:203#/definitions/program_id
  quantity:
    $ref: apicurio:203#/definitions/quantity
  rate:
    $ref: apicurio:203#/definitions/rate
  rate_code:
    $ref: apicurio:203#/definitions/rate_code
  rate_qualifiers:
    $ref: apicurio:203#/definitions/rate_qualifiers
  rate_totals:
    $ref: apicurio:203#/definitions/rate_totals
  rate_type:
    $ref: apicurio:203#/definitions/rate_type
  reservation:
    $ref: apicurio:203#/definitions/reservation
  response_details:
    $ref: apicurio:203#/definitions/response_details
  response_message:
    $ref: apicurio:203#/definitions/response_message
  response_reason:
    $ref: apicurio:203#/definitions/response_reason
  rest_method:
    $ref: apicurio:203#/definitions/rest_method
  revised:
    $ref: apicurio:203#/definitions/revised
  sipp_code:
    $ref: apicurio:203#/definitions/sipp_code
  status:
    $ref: apicurio:203#/definitions/status
  success_details:
    $ref: apicurio:203#/definitions/success_details
  success_response:
    $ref: apicurio:203#/definitions/success_response
  success_status:
    $ref: apicurio:203#/definitions/success_status
  tax:
    $ref: apicurio:203#/definitions/tax
  tax_type:
    $ref: apicurio:203#/definitions/tax_type
  term:
    $ref: apicurio:203#/definitions/term
  term_type:
    $ref: apicurio:203#/definitions/term_type
  totals:
    $ref: apicurio:203#/definitions/totals
  train_class:
    $ref: apicurio:203#/definitions/train_class
  train_code:
    $ref: apicurio:203#/definitions/train_code
  train_journey:
    $ref: apicurio:203#/definitions/train_journey
  transaction:
    $ref: apicurio:203#/definitions/transaction
  transaction_id:
    $ref: apicurio:203#/definitions/transaction_id
  transmission:
    $ref: apicurio:203#/definitions/transmission
  transport_mode:
    $ref: apicurio:203#/definitions/transport_mode
  type:
    $ref: apicurio:203#/definitions/type
  url:
    $ref: apicurio:203#/definitions/url
  vehical:
    $ref: apicurio:203#/definitions/vehical
  vehical_capacity:
    $ref: apicurio:203#/definitions/vehical_capacity
  vehical_category:
    $ref: apicurio:203#/definitions/vehical_category
  vehical_features:
    $ref: apicurio:203#/definitions/vehical_features
  vehicle:
    $ref: apicurio:203#/definitions/vehicle
  week_day:
    $ref: apicurio:203#/definitions/week_day
  partner:
    $ref: apicurio:203#/definitions/partner
  loyalty_discounts:
    $ref: apicurio:203#/definitions/loyalty_discounts
  partner_program_v1_response:
    description: All the available Discounts and free extra product details for Avis
      Budget Group vehicles which are applicable to passengers loyalty cards.
    type: object
    properties:
      status:
        $ref: '#/definitions/success_status'
        description: ""
      transaction:
        $ref: '#/definitions/transaction'
        description: ""
      domain:
        $ref: '#/definitions/domain'
        description: ""
      loyalty_discounts:
        $ref: '#/definitions/loyalty_discounts'
        description: ""
    example:
      status:
        request_time: 2018-10-25T12:01:54Z
        success:
        - code: "200"
          message: Success
          details: Loyalty details are successfully retrieved.
      transaction:
        id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
        system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
      domain:
        language: EN
      loyalty_discounts:
      - rate_qualifiers:
          partner_loyalty:
            program: Voyageur
          partner_discount:
            program: San carte
        mapped_discounts:
        - brand: Avis
          code: X5212064
          percent: 15
          free_options:
            eligible_extras:
              quantity: 1
            eligible_codes:
            - ADD
            - GPS
            - BBS
            - CBS
            - CSS
            - SKR
            - SNC
        - brand: Budget
          code: L824502
          percent: 10
          free_options:
            eligible_extras:
              quantity: 0
        best_discount: true
      - rate_qualifiers:
          partner_loyalty:
            program: GRAND VOYAGEUR LE CLUB
          partner_discount:
            program: Carte Jeune
        mapped_discounts:
        - brand: Avis
          code: X5212067
          percent: 10
          free_options:
            eligible_extras:
              quantity: 1
            eligible_codes:
            - ADD
            - GPS
            - BBS
            - CBS
            - CSS
            - SKR
            - SNC
        - brand: Budget
          code: L824502
          percent: 10
          free_options:
            eligible_extras:
              quantity: 0
  partner_v1_response:
    title: Loyalty tier lookup information
    description: Partner loyalty and discount cards with associated ABG discounts
      codes and free options.
    type: object
    properties:
      status:
        $ref: '#/definitions/success_status'
        description: ""
      transaction:
        $ref: '#/definitions/transaction'
        description: ""
      domain:
        $ref: '#/definitions/domain'
        description: ""
      loyalty_discounts:
        $ref: '#/definitions/loyalty_discounts'
        description: ""
    example:
      status:
        request_time: 2018-10-25T12:01:54Z
        success:
        - code: "200"
          message: Success
          details: Loyalty details are successfully retrieved.
      transaction:
        id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
        system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
      domain:
        language: EN
      loyalty_discounts:
      - rate_qualifiers:
          partner_loyalty:
            program: SANS CARTE
          partner_discount:
            program: SANS CARTE
        mapped_discounts:
        - brand: Avis
          code: X5212058
          percent: 10
          free_options:
            eligible_extras:
              quantity: 0
        - brand: Budget
          code: L824502
          percent: 10
          free_options:
            eligible_extras:
              quantity: 0
      - rate_qualifiers:
          partner_loyalty:
            program: VOYAGEUR
          partner_discount:
            program: SANS CARTE
        mapped_discounts:
        - brand: Avis
          code: X5212059
          percent: 15
          free_options:
            eligible_extras:
              quantity: 1
            eligible_codes:
            - ADD
            - GPS
            - BBS
            - CBS
            - CSS
            - SKR
            - SNC
        - brand: Budget
          code: L824502
          percent: 15
          free_options:
            eligible_extras:
              quantity: 0
responses:
  partner_v1_response:
    description: ""
    schema:
      $ref: '#/definitions/partner_v1_response'
    examples:
      application/json:
        status:
          request_time: 2018-10-25T12:01:54Z
          success:
          - code: "200"
            message: Success
            details: Loyalty details are successfully retrieved.
        transaction:
          id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
          system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
        domain:
          language: EN
        loyalty_discounts:
        - rate_qualifiers:
            partner_loyalty:
              program: SANS CARTE
            partner_discount:
              program: SANS CARTE
          mapped_discounts:
          - brand: Avis
            code: X5212058
            percent: 10
            free_options:
              eligible_extras:
                quantity: 0
          - brand: Budget
            code: L824502
            percent: 10
            free_options:
              eligible_extras:
                quantity: 0
        - rate_qualifiers:
            partner_loyalty:
              program: VOYAGEUR
            partner_discount:
              program: SANS CARTE
          mapped_discounts:
          - brand: Avis
            code: X5212059
            percent: 15
            free_options:
              eligible_extras:
                quantity: 1
              eligible_codes:
              - ADD
              - GPS
              - BBS
              - CBS
              - CSS
              - SKR
              - SNC
          - brand: Budget
            code: L824502
            percent: 15
            free_options:
              eligible_extras:
                quantity: 0
  partner_program_v1_response:
    description: ""
    schema:
      $ref: '#/definitions/partner_program_v1_response'
    examples:
      application/json:
        status:
          request_time: 2018-10-25T12:01:54Z
          success:
          - code: "200"
            message: Success
            details: Loyalty details are successfully retrieved.
        transaction:
          id: 227a1700-43e1-11e9-95ce-e6a7a0e31bec
          system_id: C56a1700-43e1-11e9-95ce-e6a7a0e31bec
        domain:
          language: EN
        loyalty_discounts:
        - rate_qualifiers:
            partner_loyalty:
              program: Voyageur
            partner_discount:
              program: San carte
          mapped_discounts:
          - brand: Avis
            code: X5212064
            percent: 15
            free_options:
              eligible_extras:
                quantity: 1
              eligible_codes:
              - ADD
              - GPS
              - BBS
              - CBS
              - CSS
              - SKR
              - SNC
          - brand: Budget
            code: L824502
            percent: 10
            free_options:
              eligible_extras:
                quantity: 0
          best_discount: true
        - rate_qualifiers:
            partner_loyalty:
              program: GRAND VOYAGEUR LE CLUB
            partner_discount:
              program: Carte Jeune
          mapped_discounts:
          - brand: Avis
            code: X5212067
            percent: 10
            free_options:
              eligible_extras:
                quantity: 1
              eligible_codes:
              - ADD
              - GPS
              - BBS
              - CBS
              - CSS
              - SKR
              - SNC
          - brand: Budget
            code: L824502
            percent: 10
            free_options:
              eligible_extras:
                quantity: 0
  error_responce_406:
    description: The requested resource is capable of generating only content not
      acceptable according to the Accept headers sent in the request.
    schema:
      $ref: '#/definitions/error_406'
    examples:
      application/json:
        status:
          request_time: 2019-01-04T15:15:30Z
          request_errors: 1
          errors:
          - code: "406"
            message: Not Accecptable
            reason: Not Accecptable
            details: org.mule.module.apikit.exception.NotAcceptableException
  error_response_400:
    description: 400 Bad Request is returned when the request could not be understood
      by the server. 400 includes missing required values, invalid data types, minimum/maximum
      values, ranges and format.
    schema:
      $ref: '#/definitions/error_400'
    examples:
      application/json:
        status:
          request_time: 2019-01-04T15:15:30Z
          request_errors: 1
          errors:
          - code: "400"
            message: Bad Request
            reason: invalid_request
            details: '- Missing required field ''brand'''
          - code: "400"
            message: Bad Request
            reason: invalid_request
            details: '- Invalid element <AVIS>.'
          - code: "14528"
            message: Bad Request
            reason: Invalid rate_code.
            details: Rate Code entered is invalid.
          - code: "14184"
            message: Bad Request
            reason: Last name and customer id combination is invalid.
            details: 'Last name does not match the wizard number '
          - code: "14441"
            message: Bad Request
            reason: Bad Request
            details: Bad Request
          - code: "1112"
            message: Bad Request
            reason: Invalid coupon_code and IATA number combination.
            details: This coupon requires an IATA / ARC number.  Please enter your
              number below or remove the coupon from this reservation.
          - code: "14299"
            message: Bad Request
            reason: Bad Request
            details: Invalid insurance details
          - code: "13213"
            message: Bad Request
            reason: Country Code is invalid
            details: Please enter a valid Country Code.
          - code: "14442"
            message: Bad Request
            reason: RENTAL DURATION LESS THAN MINIMUM
            details: RENTAL DURATION LESS THAN MINIMUM
          - code: "1103"
            message: Bad Request
            reason: Invalid Country/Coupon Code
            details: This station does not participate.  Valid at corporate/participating
              licensees in the U.S. (excluding Alaska, Hawaii and the New York Metro),
              Canada, Australia, New Zealand, France, Puerto Rico, United Kingdom
              and U.S. Virgin Islands.
          - code: "14372"
            message: Bad Request
            reason: Invalid coupon_code
            details: The Coupon Number entered is invalid.
          - code: "14374"
            message: Bad Request
            reason: coupon_code is invalid for the given time frame.
            details: The Coupon Number entered does not meet the minimum days requirement.
              Please check the terms and conditions or remove to continue this reservation.
          - code: "19076"
            message: Bad Request
            reason: Invalid loyalty_code membership_code
            details: Membership Number entered is invalid.
          - code: "235"
            message: Bad Request
            reason: loyalty_code and loyalty_company_id are required parameters for
              the selection of Frequent Travel Program.
            details: If you have selected a Frequent Traveler Program, than you must
              enter a Membership Number
          - code: "14075"
            message: Bad Request
            reason: RateCode requires a valid discount number in the request.
            details: ' The rate code you entered requires a discount number. Please
              go back and enter your discount number or remove the rate code you entered.'
          - code: "1798"
            message: Bad Request
            reason: Invalid discount_number.
            details: Invalid AWD
          - code: "14022"
            message: Bad Request
            reason: Invalid vehicle_class_code
            details: Requested Car Group is invalid.
          - code: "12012"
            message: Bad Request
            reason: Invalid city
            details: MSGCD_E_WIZ_CITY_NAME_REQUIRED
          - code: "14105"
            message: Bad Request
            reason: Invalid rate_code.
            details: Invalid Vehicle rate code and class code combination for the
              provided brand.
          - code: "208"
            message: Bad Request
            reason: Invalid customer_id.
            details: Invalid Wizard number for the customer.
          - code: "205"
            message: Bad Request
            reason: Invalid dropoff_location.
            details: Invalid Drop off location
          - code: "203"
            message: Bad Request
            reason: Invalid pickup_location.
            details: Invalid Pick up location
          - code: "231"
            message: Bad Request
            reason: Invalid pickup_date.
            details: You selected a date/time prior to the current time
          - code: "232"
            message: Bad Request
            reason: dropoff_date is prior to pickup_date.
            details: Return Date cannot be prior or same to the Pick-Up Date
          - code: "237"
            message: Bad Request
            reason: Invalid flight carrier_name.
            details: Please select valid Airline
          - code: "239"
            message: Bad Request
            reason: Invalid filght carrier_code.
            details: Please enter a valid flight number. Flight Number format is a
              maximum 4 numbers. Please omit letters from your flight number
          - code: "234"
            message: Bad Request
            reason: Invalid frequent_flyer_number.
            details: If you have entered a Membership Number, then you must select
              a Frequent Traveler Program.
          - code: "209"
            message: Bad Request
            reason: Invalid coupon_number.
            details: Please enter a valid Coupon Number.
          - code: "216"
            message: Bad Request
            reason: Invalid discount_number.
            details: The discount number is invalid for the given Avis.
          - code: "150004"
            message: Bad Request
            reason: last_name and confirmation_number combination is invalid.
            details: Last name entered does not match with the confirmation number
          - code: "19082"
            message: Bad Request
            reason: Bad Request
            details: Bad Request from e-Com backend.
          - code: "1122"
            message: Bad Request
            reason: Coupon_code is expired.
            details: Coupon requires a minimum length of 3 days. Please select a rate
              to continue (coupon will be removed).
          - code: "300100"
            message: Bad Request
            reason: PrePayReservationCurrency must be required
            details: PrePayReservationCurrency must be required
          - code: "300101"
            message: Bad Request
            reason: PrePayReservationAmount must be required
            details: PrePayReservationAmount must be required
          - code: "300111"
            message: Bad Request
            reason: Prepay information details are required for the Prepay type.
            details: Prepay Information must be required.
          - code: "900909"
            message: Bad Request
            reason: cvv is invalid for the provided Credit Card.
            details: cvv is invalid for the provided Credit Card.
          - code: "300102"
            message: Bad Request
            reason: Credit Card details are mandatory.
            details: Valid Credit Card Details must be required
          - code: "14220"
            message: Bad Request
            reason: Payment details are invalid.
            details: The number either doesn't match the card type or is the wrong
              length. Please check your entries and try again
          - code: "215"
            message: Bad Request
            reason: Invalid email.
            details: Invalid email address
          - code: "14025"
            message: Bad Request
            reason: Bad Request.
            details: Bad Request from e-Com backend.
          - code: "19001"
            message: Bad Request
            reason: country_code,state_name and postal_code combination is invalid.
            details: Invalid zip code.
          - code: "212"
            message: Bad Request
            reason: last_name is required.
            details: Last Name is required
          - code: "210"
            message: Bad Request
            reason: first_name is mandatory.
            details: First Name is required
          - code: "14126"
            message: Bad Request
            reason: dropoff_date and pickup_date combination is invalid.
            details: Pick-up Date can not be after Return Date.
          - code: "14129"
            message: Bad Request
            reason: Invalid pickup_date.
            details: pickup_date is less than the current date.
          - code: "226"
            message: Bad Request
            reason: Invalid dropoff_location.
            details: There are no locations available for your Return address.
          - code: "225"
            message: Bad Request
            reason: Invalid pickup_location.
            details: There are no locations available for your Pick-up address.
          - code: "227"
            message: Bad Request
            reason: Invalid pickup_location and dropoff_location.
            details: Sorry! No Avis locations are available in address provided.
          - code: "219"
            message: Bad Request
            reason: Missing partner_country_code.
            details: Country of residence is required.
          - code: "19074"
            message: Bad Request
            reason: Invalid Vehicle rate code and class code combination for the provided
              brand.
            details: ' Rate Code entered is invalid.'
          - code: "1005"
            message: Bad Request
            reason: 'e-Com rejected the request due to data issue. '
            details: Request is invalid.
          - code: "1109"
            message: Bad Request
            reason: Coupon is applicable only for certain discount types.
            details: 'This coupon requires one of the following discount number types:
              {0}.'
          - code: "1203"
            message: Bad Request
            reason: Invalid coupon and discount combination.
            details: This coupon {0} may only be used with a specific AWD number (see
              offer terms). Please enter this AWD number to continue or select from
              available cars to continue without the coupon.
          - code: "1124"
            message: Bad Request
            reason: Invalid coupon and brand combination.
            details: This coupon may only be used on  W G car groups. Please select
              from one of these groups or select a different one to proceed without
              the coupon.
          - code: "200"
            message: Bad Request
            reason: Brand is a required field.
            details: Brand is a required field.
          - code: "202"
            message: Bad Request
            reason: pickup_location is a required field.
            details: pickup_location is a required field.
          - code: "206"
            message: Bad Request
            reason: pickup_location is a required field.
            details: pickup_location is a required field.
          - code: "204"
            message: Bad Request
            reason: dropoff_location is a required field.
            details: dropoff_location is a required field.
          - code: "207"
            message: Bad Request
            reason: dropoff_location is a required field.
            details: dropoff_location is a required field.
          - code: "217"
            message: Bad Request
            reason: vehicle_class_code is a required field.
            details: vehicle_class_code is a required field and it is associated with
              rate_code.
          - code: "218"
            message: Bad Request
            reason: rate_code is a required field.
            details: rate_code is a required field and it is associated with the vehicle_class_code.
          - code: "220"
            message: Bad Request
            reason: Confirmation Number is required field.
            details: Confirmation Number is required field.
          - code: "22224"
            message: Bad Request
            reason: A One-Way Rental between given pickup_location and dropoff_location
              is not available
            details: A One-Way Rental between these 2  locations cannot be booked
              online.
  error_response_404:
    description: "404 Not Found is returned when server cannot find the matching request\
      \ URI (either due to no results, or because of a non-existent endpoint or resource).\
      \ Server may also respond with this status code when there is 401 or 403, which\
      \ the service wants to mask for security reasons.\r\n\r\n"
    schema:
      $ref: '#/definitions/error_404'
    examples:
      application/json:
        status:
          request_time: 2019-01-04T15:15:30Z
          request_errors: 1
          errors:
          - code: "404"
            message: Resource Not Found
            reason: resource_failure
            details: Server cannot find the requested resource. This may be due to
              incorrect URI or a resource that is not available.
          - code: "223"
            message: Not Found
            reason: Invalid pickup_location.
            details: The pick-up location entered is Sold Out for the dates you have
              entered
          - code: "14036"
            message: Not Found
            reason: Reservation already cancelled
            details: Reservation is already cancelled for the given confirmation_number.
          - code: "14381"
            message: Not Found
            reason: 'A One-Way Rental between given pickup_location and dropoff_location
              is not available '
            details: 'A One-Way Rental between given pickup_location and dropoff_location
              is not available '
  error_response_405:
    description: A request method is not supported for the requested resource; for
      example, a GET request on a form that requires data to be presented via POST,
      or a PUT request on a read-only resource.
    schema:
      $ref: '#/definitions/error_405'
    examples:
      application/json:
        status:
          request_time: 2019-01-04T15:15:30Z
          request_errors: 1
          errors:
          - code: "405"
            message: Method Not Allowed
            reason: Method Not Allowed
            details: org.mule.module.apikit.exception.MethodNotAllowedException
  error_response_415:
    description: The request entity has a media type which the server or resource
      does not support. For example, the client uploads an image as image/svg+xml,
      but the server requires that images use a different format.
    schema:
      $ref: '#/definitions/error_415'
    examples:
      application/json:
        status:
          request_time: 2018-10-17T13:05:10Z
          request_errors: 1
          errors:
          - code: "415"
            message: Unsupported Media Type
            reason: Unsupported Media Type
            details: org.mule.module.apikit.exception.UnsupportedMediaTypeException
  error_response_500:
    description: 500 Internal Server Error is returned when a system or application
      error has occurred. It generally indicates that something unexpected has gone
      wrong on the server. This is used for a standard server side exception for a
      persistent error on the server side.
    schema:
      $ref: '#/definitions/error_500'
    examples:
      application/json:
        status:
          request_time: 2019-01-04T15:15:30Z
          request_errors: 1
          errors:
          - code: "40018"
            message: Service exception
            reason: Service exception
            details: Socket timeout from IMS Connect
          - code: "610"
            message: Service exception
            reason: System exception from e-com backend.
            details: System Exception occurred during location search.Please check
              the log for details.
securityDefinitions:
  OAuth2.0:
    flow: application
    tokenUrl: https://stage.abgapiservices.com/oauth/token/v1
    scopes:
      scope-1: ""
    type: oauth2
